/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as LangTermsOfUseRouteImport } from './routes/$lang/terms-of-use'
import { Route as LangPrivacyPolicyRouteImport } from './routes/$lang/privacy-policy'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products/index'
import { Route as LangProductsSlugRouteImport } from './routes/$lang/products/$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTermsOfUseRoute = LangTermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => LangRoute,
} as any)
const LangPrivacyPolicyRoute = LangPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-use': typeof LangTermsOfUseRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-use': typeof LangTermsOfUseRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/products': typeof LangProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy-policy': typeof LangPrivacyPolicyRoute
  '/$lang/terms-of-use': typeof LangTermsOfUseRoute
  '/api/contact': typeof ApiContactRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/products/': typeof LangProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-use'
    | '/api/contact'
    | '/$lang/'
    | '/$lang/products/$slug'
    | '/$lang/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-use'
    | '/api/contact'
    | '/$lang'
    | '/$lang/products/$slug'
    | '/$lang/products'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/contact'
    | '/$lang/privacy-policy'
    | '/$lang/terms-of-use'
    | '/api/contact'
    | '/$lang/'
    | '/$lang/products/$slug'
    | '/$lang/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/terms-of-use': {
      id: '/$lang/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/$lang/terms-of-use'
      preLoaderRoute: typeof LangTermsOfUseRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/privacy-policy': {
      id: '/$lang/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$lang/privacy-policy'
      preLoaderRoute: typeof LangPrivacyPolicyRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangContactRoute: typeof LangContactRoute
  LangPrivacyPolicyRoute: typeof LangPrivacyPolicyRoute
  LangTermsOfUseRoute: typeof LangTermsOfUseRoute
  LangIndexRoute: typeof LangIndexRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangContactRoute: LangContactRoute,
  LangPrivacyPolicyRoute: LangPrivacyPolicyRoute,
  LangTermsOfUseRoute: LangTermsOfUseRoute,
  LangIndexRoute: LangIndexRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
